# .streamlit/secrets.toml
# Xóa SENDER_EMAIL và SENDER_APP_PASS cũ — email giờ do Google Apps Script gửi

TELEGRAM_BOT_TOKEN = "8904962328:AAFi_7YZkQnv_cMmBmwdnMeQsnb6sa6q0BY"   # Token bot Telegram của bạn
TELEGRAM_CHAT_ID   = "7543346250"              # Chat ID của bạn (admin)
GAS_WEBHOOK_URL    = "https://script.google.com/macros/s/AKfycbzI-msHaThZqq8s2BRWFCZddNksyrN8N6JV1g3XNeBtkUji4VneiRDSjTXf9XZ1cHiKXA/exec"  # URL deploy GAS
